export interface LanguageCodeMapping {
    language: string;
    codes: string[];
}

export const supportedLanguages: LanguageCodeMapping[] = [
    { language: "Afrikaans", codes: ["af"] },
    { language: "Albanian", codes: ["sq"] },
    { language: "Amharic", codes: ["am"] },
    { language: "Arabic", codes: ["ar"] },
    { language: "Armenian", codes: ["hy"] },
    { language: "Assamese", codes: ["as"] },
    { language: "Aymara", codes: ["ay"] },
    { language: "Azerbaijani", codes: ["az"] },
    { language: "Bambara", codes: ["bm"] },
    { language: "Basque", codes: ["eu"] },
    { language: "Belarusian", codes: ["be"] },
    { language: "Bengali", codes: ["bn"] },
    { language: "Bhojpuri", codes: ["bho"] },
    { language: "Bosnian", codes: ["bs"] },
    { language: "Bulgarian", codes: ["bg"] },
    { language: "Catalan", codes: ["ca"] },
    { language: "Cebuano", codes: ["ceb"] },
    { language: "Chinese (Simplified)", codes: ["zh-CN", "zh"] },
    { language: "Chinese (Traditional)", codes: ["zh-TW"] },
    { language: "Corsican", codes: ["co"] },
    { language: "Croatian", codes: ["hr"] },
    { language: "Czech", codes: ["cs"] },
    { language: "Danish", codes: ["da"] },
    { language: "Dhivehi", codes: ["dv"] },
    { language: "Dogri", codes: ["doi"] },
    { language: "Dutch", codes: ["nl"] },
    { language: "English", codes: ["en"] },
    { language: "Esperanto", codes: ["eo"] },
    { language: "Estonian", codes: ["et"] },
    { language: "Ewe", codes: ["ee"] },
    { language: "Filipino (Tagalog)", codes: ["fil"] },
    { language: "Finnish", codes: ["fi"] },
    { language: "French", codes: ["fr"] },
    { language: "Frisian", codes: ["fy"] },
    { language: "Galician", codes: ["gl"] },
    { language: "Georgian", codes: ["ka"] },
    { language: "German", codes: ["de"] },
    { language: "Greek", codes: ["el"] },
    { language: "Guarani", codes: ["gn"] },
    { language: "Gujarati", codes: ["gu"] },
    { language: "Haitian Creole", codes: ["ht"] },
    { language: "Hausa", codes: ["ha"] },
    { language: "Hawaiian", codes: ["haw"] },
    { language: "Hebrew", codes: ["he", "iw"] },
    { language: "Hindi", codes: ["hi"] },
    { language: "Hmong", codes: ["hmn"] },
    { language: "Hungarian", codes: ["hu"] },
    { language: "Icelandic", codes: ["is"] },
    { language: "Igbo", codes: ["ig"] },
    { language: "Ilocano", codes: ["ilo"] },
    { language: "Indonesian", codes: ["id"] },
    { language: "Irish", codes: ["ga"] },
    { language: "Italian", codes: ["it"] },
    { language: "Japanese", codes: ["ja"] },
    { language: "Javanese", codes: ["jv", "jw"] },
    { language: "Kannada", codes: ["kn"] },
    { language: "Kazakh", codes: ["kk"] },
    { language: "Khmer", codes: ["km"] },
    { language: "Kinyarwanda", codes: ["rw"] },
    { language: "Konkani", codes: ["gom"] },
    { language: "Korean", codes: ["ko"] },
    { language: "Krio", codes: ["kri"] },
    { language: "Kurdish", codes: ["ku"] },
    { language: "Kurdish (Sorani)", codes: ["ckb"] },
    { language: "Kyrgyz", codes: ["ky"] },
    { language: "Lao", codes: ["lo"] },
    { language: "Latin", codes: ["la"] },
    { language: "Latvian", codes: ["lv"] },
    { language: "Lingala", codes: ["ln"] },
    { language: "Lithuanian", codes: ["lt"] },
    { language: "Luganda", codes: ["lg"] },
    { language: "Luxembourgish", codes: ["lb"] },
    { language: "Macedonian", codes: ["mk"] },
    { language: "Maithili", codes: ["mai"] },
    { language: "Malagasy", codes: ["mg"] },
    { language: "Malay", codes: ["ms"] },
    { language: "Malayalam", codes: ["ml"] },
    { language: "Maltese", codes: ["mt"] },
    { language: "Maori", codes: ["mi"] },
    { language: "Marathi", codes: ["mr"] },
    { language: "Meiteilon (Manipuri)", codes: ["mni-Mtei"] },
    { language: "Mizo", codes: ["lus"] },
    { language: "Mongolian", codes: ["mn"] },
    { language: "Myanmar (Burmese)", codes: ["my"] },
    { language: "Nepali", codes: ["ne"] },
    { language: "Norwegian", codes: ["no"] },
    { language: "Nyanja (Chichewa)", codes: ["ny"] },
    { language: "Odia (Oriya)", codes: ["or"] },
    { language: "Oromo", codes: ["om"] },
    { language: "Pashto", codes: ["ps"] },
    { language: "Persian", codes: ["fa"] },
    { language: "Polish", codes: ["pl"] },
    { language: "Portuguese (Portugal, Brazil)", codes: ["pt"] },
    { language: "Punjabi", codes: ["pa"] },
    { language: "Quechua", codes: ["qu"] },
    { language: "Romanian", codes: ["ro"] },
    { language: "Russian", codes: ["ru"] },
    { language: "Samoan", codes: ["sm"] },
    { language: "Sanskrit", codes: ["sa"] },
    { language: "Scots Gaelic", codes: ["gd"] },
    { language: "Sepedi", codes: ["nso"] },
    { language: "Serbian", codes: ["sr"] },
    { language: "Sesotho", codes: ["st"] },
    { language: "Shona", codes: ["sn"] },
    { language: "Sindhi", codes: ["sd"] },
    { language: "Sinhala (Sinhalese)", codes: ["si"] },
    { language: "Slovak", codes: ["sk"] },
    { language: "Slovenian", codes: ["sl"] },
    { language: "Somali", codes: ["so"] },
    { language: "Spanish", codes: ["es"] },
    { language: "Sundanese", codes: ["su"] },
    { language: "Swahili", codes: ["sw"] },
    { language: "Swedish", codes: ["sv"] },
    { language: "Tagalog (Filipino)", codes: ["tl"] },
    { language: "Tajik", codes: ["tg"] },
    { language: "Tamil", codes: ["ta"] },
    { language: "Tatar", codes: ["tt"] },
    { language: "Telugu", codes: ["te"] },
    { language: "Thai", codes: ["th"] },
    { language: "Tigrinya", codes: ["ti"] },
    { language: "Tsonga", codes: ["ts"] },
    { language: "Turkish", codes: ["tr"] },
    { language: "Turkmen", codes: ["tk"] },
    { language: "Twi (Akan)", codes: ["ak"] },
    { language: "Ukrainian", codes: ["uk"] },
    { language: "Urdu", codes: ["ur"] },
    { language: "Uyghur", codes: ["ug"] },
    { language: "Uzbek", codes: ["uz"] },
    { language: "Vietnamese", codes: ["vi"] },
    { language: "Welsh", codes: ["cy"] },
    { language: "Xhosa", codes: ["xh"] },
    { language: "Yiddish", codes: ["yi"] },
    { language: "Yoruba", codes: ["yo"] },
    { language: "Zulu", codes: ["zu"] },
];
